# Generated by Django 2.2 on 2020-01-28 18:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0003_auto_20200127_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 1, 28, 10, 43, 46, 544956))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=255)),
                ('audience', models.CharField(max_length=255)),
                ('brief', models.CharField(max_length=255)),
                ('priority', models.CharField(blank=True, max_length=10, null=True)),
                ('stack_comp', models.CharField(blank=True, max_length=255, null=True)),
                ('database', models.CharField(blank=True, max_length=255, null=True)),
                ('api', models.CharField(blank=True, max_length=255, null=True)),
                ('server', models.CharField(blank=True, max_length=255, null=True)),
                ('other_tech', models.TextField(blank=True, null=True)),
                ('work_contrib', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 1, 28, 10, 43, 46, 540924))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 10, 43, 46, 539969)),
        ),
        migrations.CreateModel(
            name='Wireframes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wireframe_img', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 1, 28, 10, 43, 46, 544956))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wireframes', to='app_login.Proposals')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 1, 28, 10, 43, 46, 545956))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app_login.Features')),
                ('student', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_tasks', to='app_login.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 1, 28, 10, 43, 46, 544956))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_from_instr', to='app_login.Users')),
                ('proposal', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app_login.Proposals')),
            ],
        ),
        migrations.AddField(
            model_name='proposals',
            name='instructor',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_to_review', to='app_login.Users'),
        ),
        migrations.AddField(
            model_name='proposals',
            name='manager',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_created', to='app_login.Users'),
        ),
        migrations.AddField(
            model_name='proposals',
            name='student',
            field=models.ManyToManyField(related_name='proposal_joined', to='app_login.Users'),
        ),
        migrations.AddField(
            model_name='features',
            name='proposal',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='app_login.Proposals'),
        ),
    ]
