# Generated by Django 2.2 on 2020-01-28 20:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0007_auto_20200128_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='manager',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_created', to='app_login.Users'),
        ),
        migrations.AddField(
            model_name='features',
            name='student',
            field=models.ManyToManyField(related_name='feature_joined', to='app_login.Users'),
        ),
        migrations.AlterField(
            model_name='features',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 12, 7, 32, 56731)),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 12, 7, 32, 56731)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 12, 7, 32, 56731)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 12, 7, 32, 56731)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 12, 7, 32, 25488)),
        ),
        migrations.AlterField(
            model_name='wireframes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 12, 7, 32, 56731)),
        ),
    ]
