# Generated by Django 2.2 on 2020-01-30 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0019_auto_20200129_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='status_rev',
            field=models.CharField(default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='features',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 43, 32, 232648)),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 43, 32, 228659)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 43, 32, 232648)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 43, 32, 233650)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 43, 32, 195750)),
        ),
        migrations.AlterField(
            model_name='wireframes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 43, 32, 231652)),
        ),
    ]
